[package]
name = "upvpn-daemon"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0"
authors = ["upvpn LLC"]
homepage = "https://upvpn.app"
repository = "https://github.com/upvpn/upvpn-app"

[dependencies]
clap = "4.2.7"
async-trait = "0.1.68"
futures = "0.3.28"
hyper = "0.14.26"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "signal", "macros", "sync", "fs"] }
tokio-stream = { version = "0.1.12", features = ["sync"] }
tonic = "0.9.2"
tower = "0.4.13"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["default", "env-filter", "tracing-log"] }
upvpn-config = {path = "../upvpn-config"}
upvpn-controller = {path = "../upvpn-controller"}
upvpn-server = {path = "../upvpn-server"}
upvpn-types = {path = "../upvpn-types"}
upvpn-entity = {path = "../upvpn-entity"}
upvpn-migration = {path = "../upvpn-migration"}
sea-orm = { version = "0.11.2", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
chrono = "0.4.24"
talpid-core = {git = "ssh://git@github.com/upvpn/mullvadvpn-app.git", rev = "2023.3.upvpn"}
talpid-types = {git = "ssh://git@github.com/upvpn/mullvadvpn-app.git", rev = "2023.3.upvpn"}
talpid-platform-metadata = {git = "ssh://git@github.com/upvpn/mullvadvpn-app.git", rev = "2023.3.upvpn"}
futures-channel = "0.3.28"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
libc = "0.2"
lazy_static = "1.0"
backoff = { version = "0.4.0", features = ["tokio"] }

[target.'cfg(unix)'.dependencies]
nix = "0.26.2"

[target.'cfg(windows)'.dependencies]
windows-service = "0.6.0"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.45.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Authentication_Identity",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_Threading",
]
